PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Candidato (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  senha TEXT NOT NULL,
  estadoAfiliacao TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Endereco (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  candidato_id INTEGER NOT NULL,
  logradouro TEXT NOT NULL,
  numero INTEGER NOT NULL,
  complemento TEXT NOT NULL,
  bairro TEXT NOT NULL,
  cidade TEXT NOT NULL,
  uf TEXT NOT NULL,
  cep TEXT NOT NULL,
  FOREIGN KEY (candidato_id) REFERENCES Candidato(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Termo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  versao TEXT NOT NULL,
  conteudo TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TermoItem (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  termo_id INTEGER NOT NULL,
  condicao TEXT NOT NULL,
  FOREIGN KEY (termo_id) REFERENCES Termo(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Pedido (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  candidato_id INTEGER NOT NULL,
  termo_id INTEGER NOT NULL,
  data_aceite TEXT NOT NULL,
  aceito INTEGER NOT NULL,
  FOREIGN KEY (candidato_id) REFERENCES Candidato(id) ON DELETE CASCADE,
  FOREIGN KEY (termo_id) REFERENCES Termo(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PerfilVoluntario (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  candidato_id INTEGER NOT NULL,
  bibliografia TEXT NOT NULL,
  disponibilidade TEXT NOT NULL,
  preferencias TEXT NOT NULL,
  FOREIGN KEY (candidato_id) REFERENCES Candidato(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Habilidade (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  perfil_id INTEGER NOT NULL,
  nome TEXT NOT NULL,
  descricao TEXT NOT NULL,
  FOREIGN KEY (perfil_id) REFERENCES PerfilVoluntario(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Interesse (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  perfil_id INTEGER NOT NULL,
  nome TEXT NOT NULL,
  descricao TEXT NOT NULL,
  FOREIGN KEY (perfil_id) REFERENCES PerfilVoluntario(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PessoaFisica (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  candidato_id INTEGER NOT NULL,
  nome TEXT NOT NULL,
  cpf TEXT NOT NULL,
  sexo TEXT NOT NULL,
  data_nascimento TEXT NOT NULL,
  nacionalidade TEXT NOT NULL,
  profissao TEXT NOT NULL,
  FOREIGN KEY (candidato_id) REFERENCES Candidato(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PessoaJuridica (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  candidato_id INTEGER NOT NULL,
  cnpj TEXT NOT NULL,
  razao_social TEXT NOT NULL,
  FOREIGN KEY (candidato_id) REFERENCES Candidato(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Representante (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pessoa_juridica_id INTEGER NOT NULL,
  nome TEXT NOT NULL,
  doc_identificacao TEXT NOT NULL,
  FOREIGN KEY (pessoa_juridica_id) REFERENCES PessoaJuridica(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Certidao (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pessoa_juridica_id INTEGER NOT NULL,
  tipo TEXT NOT NULL,
  nome_arquivo TEXT NOT NULL,
  caminho TEXT NOT NULL,
  data_upload TEXT NOT NULL,
  FOREIGN KEY (pessoa_juridica_id) REFERENCES PessoaJuridica(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TokenValidacaoEmail (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  candidato_id INTEGER NOT NULL,
  token TEXT NOT NULL,
  expira_em TEXT NOT NULL,
  usado INTEGER NOT NULL,
  FOREIGN KEY (candidato_id) REFERENCES Candidato(id) ON DELETE CASCADE
);
